Switch to Kotlin Regex API
VirtusLab/git-machete-intellij-plugin pull request #1035
Opened 2022-08-04 10:05 UTC by MaciejG604

2022-08-04 10:09 UTC, PawelLipski requested changes

2022-08-04 10:09 UTC, PawelLipski commented on build.gradle.kts
>  import com.virtuslab.gitmachete.buildsrc.*
Whoops pls rebase onto the fresh develop

2022-08-04 10:10 UTC, PawelLipski approved these changes

2022-08-04 10:11 UTC, PawelLipski approved these changes

2022-08-05 08:13 UTC, merged

2022-08-05 08:13 UTC, MaciejG604 commented
Can't link this PR to #1004 as there is a limit of 10 linked PRs