Hide `Slide In Branch Below Current Branch` for unmanaged branches
VirtusLab/git-machete-intellij-plugin pull request #604
Opened 2020-10-02 14:53 UTC by micpiotrowski

2020-10-03 12:04 UTC, PawelLipski approved these changes
Tested locally, works fine :)

2020-10-04 18:22 UTC, mkondratek requested changes

2020-10-04 18:22 UTC, mkondratek commented on frontendActions/src/main/java/com/virtuslab/gitmachete/frontend/actions/base/BaseSlideInBranchBelowAction.java
> -      presentation.setDescription(getString("action.GitMachete.BaseSlideInBranchBelowAction.description.disabled.no-parent"));
I would leave the desc wrt #595

2020-10-05 12:01 UTC, mkondratek approved these changes

2020-10-05 12:11 UTC, merged