Exclude `git fetch .` reflog events when inferring fork point + update deps
VirtusLab/git-machete-intellij-plugin pull request #636
Opened 2020-10-28 12:07 UTC by PawelLipski

2020-10-28 12:09 UTC, PawelLipski commented on Dockerfile
> -# netcat         => nc
No longer used once the `scripts/run-ui-tests` has been simplified

2020-10-28 17:21 UTC, mkondratek approved these changes

2020-10-28 17:21 UTC, mkondratek commented on .circleci/config.yml
> +          name: Validate Markdown ToCs
+1

2020-11-03 10:39 UTC, merged

2021-04-09 09:31 UTC, Germanstreetstyle requested changes
- [ ]

2021-04-09 09:35 UTC, PawelLipski commented
❓