Refresh machete file annotations when repo changed
VirtusLab/git-machete-intellij-plugin pull request #658
Opened 2020-12-04 11:29 UTC by micpiotrowski

2020-12-05 15:36 UTC, mkondratek approved these changes

2020-12-05 17:44 UTC, PawelLipski commented
Whooops... just got the following error, most likely right after sliding in a new branch while editor was opened:

```
com.intellij.diagnostic.PluginException: Element: class com.virtuslab.gitmachete.frontend.file.grammar.MacheteFile #Machete  because: different providers: com.virtuslab.gitmachete.frontend.file.MacheteFileViewProvider{vFile=file:///home/plipski/git-machete-intellij-plugin/.git/machete, vFileId=399317, content=VirtualFileContent{size=17}, eventSystemEnabled=true}(13a00cc6); com.virtuslab.gitmachete.frontend.file.MacheteFileViewProvider{vFile=file:///home/plipski/git-machete-intellij-plugin/.git/machete, vFileId=399317, content=VirtualFileContent{size=17}, eventSystemEnabled=true}(7ab5c6c4)
invalidated at: see attachment [Plugin: com.virtuslab.git-machete]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:335)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:68)
	at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:478)
	at com.intellij.psi.impl.source.PsiFileImpl.getTextLength(PsiFileImpl.java:324)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.restart(DaemonCodeAnalyzerImpl.java:557)
	at com.virtuslab.gitmachete.frontend.file.MacheteFileViewProvider.lambda$subscribeToGitRepositoryChanges$0(MacheteFileViewProviderFactory.java:47)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.intellij.psi.PsiInvalidElementAccessException: Element: class com.virtuslab.gitmachete.frontend.file.grammar.MacheteFile #Machete  because: different providers: com.virtuslab.gitmachete.frontend.file.MacheteFileViewProvider{vFile=file:///home/plipski/git-machete-intellij-plugin/.git/machete, vFileId=399317, content=VirtualFileContent{size=17}, eventSystemEnabled=true}(13a00cc6); com.virtuslab.gitmachete.frontend.file.MacheteFileViewProvider{vFile=file:///home/plipski/git-machete-intellij-plugin/.git/machete, vFileId=399317, content=VirtualFileContent{size=17}, eventSystemEnabled=true}(7ab5c6c4)
invalidated at: see attachment
	... 33 more
```

2020-12-05 19:04 UTC, mkondratek requested changes
🙅

2020-12-06 11:26 UTC, PawelLipski commented
...yeah, the above seems to show up pretty consistently, now I've spotted it after Slide Out as well :/

2020-12-08 11:09 UTC, PawelLipski commented on frontendFile/src/main/java/com/virtuslab/gitmachete/frontend/file/MacheteFileViewProviderFactory.java
> +        FileContentUtil.reparseFiles(project, java.util.List.of(psiFile.getVirtualFile()), true);
Pls name the `true` param, it's unclear what it means :thinking:

2020-12-08 11:14 UTC, PawelLipski approved these changes
Tested locally, works as expected :ok_hand:

2020-12-08 11:26 UTC, PawelLipski approved these changes

2020-12-10 12:47 UTC, mkondratek approved these changes

2020-12-11 16:10 UTC, merged